name: Validate Contracts

on:
  push:
    branches: [main, develop]
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts.yml'

jobs:
  validate:
    name: Validate Contract Schemas and Examples
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'contracts/package.json'
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'contracts/requirements.txt'
      
      - name: Install Node.js dependencies
        run: |
          cd contracts
          npm ci
      
      - name: Install Python dependencies
        run: |
          pip install -r contracts/requirements.txt
      
      - name: Validate all contracts (Node.js)
        run: |
          cd contracts
          npm test
      
      - name: Test Python validation script
        run: |
          python contracts/scripts/validate_inputs.py sitefit 1.0.0 contracts/sitefit/1.0.0/examples/valid/minimal.json
      
      - name: Check schema structure
        run: |
          # Verify all required files exist
          for contract in contracts/*/; do
            if [ -d "$contract" ] && [ "$(basename $contract)" != "_templates" ] && [ "$(basename $contract)" != "scripts" ]; then
              for version in "$contract"*/; do
                if [ -d "$version" ]; then
                  echo "Checking $(basename $contract)/$(basename $version)..."
                  test -f "${version}inputs.schema.json" || (echo "Missing inputs.schema.json" && exit 1)
                  test -f "${version}outputs.schema.json" || (echo "Missing outputs.schema.json" && exit 1)
                  test -f "${version}bindings.json" || (echo "Missing bindings.json" && exit 1)
                  test -f "${version}manifest.json" || (echo "Missing manifest.json" && exit 1)
                  test -f "${version}plugins.json" || (echo "Missing plugins.json" && exit 1)
                  test -f "${version}README.md" || (echo "Missing README.md" && exit 1)
                fi
              done
            fi
          done
      
      - name: Summary
        if: success()
        run: |
          echo "✅ All contract validations passed!"
          echo "📋 Validated contracts:"
          find contracts -name "inputs.schema.json" -not -path "*/node_modules/*" -not -path "*/_templates/*" | while read schema; do
            echo "  - $(dirname $schema | sed 's|contracts/||')"
          done
